### ISSUE TITLE
Feature Request: Don't move point upon commenting

### ISSUE THREAD

**Issue by jojojames** [Malabarba/comment-or-uncomment-sexp#2]
Hi! Thanks for the package. I've been using https://gist.github.com/dsedivec/ddbcc985f32d108afab86d86b8c02519 to do comment-or-uncomment sexp for a while but your package is on melpa! In ^, when commenting, the point doesn't move so you can uncomment/comment (toggle) one right after another. It'd be cool to have a user option to not move the point upon commenting.

I have something like this now but it'd be cool for the package to bake the functionality in, I think.

```
  (defun j|comment-or-uncomment-sexp (f &rest args)
    "Don't move point when toggling comments."
    (interactive)
    (save-excursion
      (comment-or-uncomment-sexp)))
```

Thanks!

**Comment by Malabarba** [comment]
While there's some merit to that, I think it also makes sense to move the point, as it makes it easier to comment out several successive sexps.
And, unfortunately, I'd rather not complicate an aleready-delicate piece of code with different behaviours depending on config options.
=/

**Comment by jojojames** [comment]
Ok, sounds good.
