### ISSUE TITLE
Doesn't comment at start of letter sometimes?

### ISSUE THREAD

**Issue by jojojames** [Malabarba/comment-or-uncomment-sexp#3]
For something like this:

```
class Trie(object):

    def __init__(self):
        self.val = ""
        self.arr = [None] * 26
        self.endOfWord = False

```

If point is at 'c' in 'class', calling comment-or-uncomment-sexp doesn't work. Moving the point one letter to the right to 'l' in 'class' comments the whole thing as expected. Point on 'd' in 'def' also works as expected.

If I try the snippet in https://gist.github.com/dsedivec/ddbcc985f32d108afab86d86b8c02519 it works in all cases.

Thanks!

**Comment by Malabarba** [comment]
Thanks for the report.

Would you like to open a PR with that fix?

**Comment by jojojames** [comment]
I'm not sure, since it seems like the implementation differs non-trivially. (Though I didn't take a too close look.)

**Comment by Malabarba** [comment]
Ok. The real truth is that I wrote this code with only lisp-like languages
in mind. :-)
In other languages the boundary of syntactic-expressions are a lot less
clear so it's much harder to implement an "always correct" solution (if
it's possible at all).

**Comment by jojojames** [comment]
Hmnn OK.
